sudo: required
services:
  - docker

before_install:
  - docker build -t kamathvijay/docker-react -f Dockerfile.dev .

script:
  - docker run kamathvijay/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "DockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-035230826561"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


