sudo: required
services:
    -docker

before_install:
  - docker build -t kamathvijay/docker-react -f Dockerfile.dev .    

  script:
    - docker run kamathvijay/docker-react npm run test -- -- coverage